# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5616f510c85317aca517a80312dc6edc06f7d3605a4c2a459e450748b9f1cee0433f511ac3cd10c37066cafdef04551ac9d4ecd5b4b5d510fcdf38ea93e1958

test:
  secret_key_base: 082dcd5076de8dee43b60870bdf47874a15c2f12e7cac8b5d0489c689ca79d5640e7ebf5b3076e7778826dba9884fc6317852e35e1566fffaaff67b969746669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
